// <auto-generated />
namespace MyClientForMSExchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddedReferencesFromClienttoEmailItemOnetoMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedReferencesFromClienttoEmailItemOnetoMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201409111147175_AddedReferencesFromClienttoEmailItemOnetoMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
